# Generated by Django 5.2.16 on 2026-07-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer'), ('TESTER', 'Tester'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('hours_per_week', models.PositiveIntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='employees.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Assignment',
                'verbose_name_plural': 'Project Assignments',
                'ordering': ['-assigned_date'],
                'constraints': [models.UniqueConstraint(fields=('project', 'employee'), name='unique_employee_project_assignment')],
            },
        ),
    ]
