# Generated by Django 5.2.16 on 2026-07-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_and_more'),
        ('projects', '0002_projectassignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'PROJECT_MANAGER')), fields=('project',), name='unique_project_manager'),
        ),
    ]
