# Generated by Django 5.2.16 on 2026-07-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectassignment_unique_project_manager'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectassignment',
            name='unique_project_manager',
        ),
    ]
