# Generated by Django 5.2.16 on 2026-07-30 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_and_more'),
        ('projects', '0004_remove_projectassignment_unique_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
