# Generated by Django 5.2.16 on 2026-07-30 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name'], name='employees_e_last_na_ae2876_idx'),
        ),
    ]
